# Generated by Django 3.2.4 on 2021-06-25 02:49

from django.db import migrations, models
import snippets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('adult', models.BooleanField(default=False)),
                ('status_text', models.CharField(max_length=120)),
                ('remark_text', models.CharField(max_length=120)),
                ('avatar', models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to=snippets.models.get_avatar_full_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
