# Generated by Django 3.1 on 2021-06-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_amphur_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='amphur',
            name='postcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
