# Generated by Django 3.1 on 2021-06-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_amphur_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amphur',
            name='postcode',
        ),
    ]
