# Generated by Django 3.2.4 on 2021-06-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20210628_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(null=True, to='userprofile.Address'),
        ),
    ]
