# Generated by Django 3.2.4 on 2021-06-30 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_auto_20210629_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='amphure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.amphures'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.provinces'),
        ),
    ]
