openapi: 3.0.2
info:
  title: Profile API
  version: v1
  description: Profile API Documents
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # optional, for documentation purposes only
paths:
  /api/profiles/:
    get:
      tags:
        - Get Profile
      security:
        - bearerAuth: []
      operationId: listProfiles
      summary: List all Profiles
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                items: {"status": "success"}
          description: 'Get Profile success'
    post:
      tags:
        - Manage Profile
      security:
        - bearerAuth: []        
      operationId: CreateProfileList
      summary: Creates a Profile
      parameters: []
      requestBody:
        description: "please enter bio_text, status_text"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date_of_birth:
                  type: string
                bio_text:
                  type: string
                status_text:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: 'Success'
  /api/profile/{id}/:
    get:
      tags:
        - Get Profiles
      security:
        - bearerAuth: []        
      operationId: RetrieveProfileDetail
      summary: List Profile by id
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: 'Get Profile success'
    put:
      tags:
        - Manage Profile
      security:
        - bearerAuth: []
      operationId: UpdateProfileDetail
      summary: Update Profile by id
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        description: "please enter bio_text, status_text"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bio_text:
                  type: string
                status_text:
                  type: string                  
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: 'Update success'
    patch:
      tags:
        - Manage Profile
      security:
        - bearerAuth: []        
      operationId: PartialUpdateProfileDetail
      summary: Partial update Profile by id
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      requestBody:
        description: "please enter bio_text, status_text can be partial update field(s)"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date_of_birth:
                  type: string
                bio_text:
                  type: string
                status_text:
                  type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: 'Update success'
    delete:
      tags:
        - Manage Profile  
      security:
        - bearerAuth: []        
      operationId: DestroyProfileDetail
      summary: Delete Profile by id
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '204':
          description: 'Delete success'
  /api/avatar/{id}/:
    patch:
      tags:
        - Avatar update
      security:
        - bearerAuth: []        
      operationId: uploadFile
      summary: Avatar update by id
      consumes:
        - multipart/form-data
      parameters:
        - name: id
          in: path
          required: true
          description: ''
          schema:
            type: string     
      requestBody:        
        required: true
        content: 
          multipart/form-data:
            schema:         
              type: object
              properties:                
                avatar:
                  type: string
                  format: binary
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Update avatar success
  /api/token/:
    post:
      tags:
        - Authentication
      description: Create a new token from username and password
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: Create a new token for gaining authenticated access to resources
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string          
  /api/token/refresh/:
    post:
      tags:
        - Authentication
      description: Get a new token (from refresh token) for gaining authenticated access to resources
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                refresh:
                  type: string
                  example: access_token
      responses:
        '201':
          description: Create a new token (from refresh token) for gaining authenticated access to resources
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string    
  /api/user/register/:
    post:
      tags:
        - Manage Profile
      operationId: RegisterNewUser
      summary: Register new user
      requestBody:
        description: "please enter email, username, password, first_name, last_name"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                  format: password
                first_name:
                  type: string
                last_name:
                  type: string                                    
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: 'Register success'
  /api/user/update/{pk}/:
    patch:
      tags:
        - Manage Profile
      security:
        - bearerAuth: []        
      operationId: UpdateFirstName_LastName
      summary: Update first_name, last_name
      parameters:
      - name: pk
        in: path
        required: true
      requestBody:
        description: "please first_name, last_name"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string                                    
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: 'Update success'